name: vision2_mobile
description: Vision 2.0 Flutter app
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  geolocator: ^13.0.1
  file_picker: ^8.1.2
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
